### ISSUE TITLE
[CRASH/Python] Check/update/Flash dongle to Thread : bytearray index out of range...

### ISSUE THREAD

**Issue by achsoftathome** [Elelabs/elelabs-zigbee-ezsp-utility#26]
Hi,

I try to test that the firmware update utility works well / update / flash and the Python script crashes with: bytearray index out of range.

OS: Ubuntu 20.04 - 64 Bits
Dongle: pontoteq 2.4 Ghz Multi-protocol USB
Python: v3.9.12
Command: sudo python3 Elelabs_EzspFwUtility.py probe -p /dev/ttyUSB1
Error: IndexError: bytearray index out of range
Device: See as /dev/ttyUSB0 & /dev/ttyUSB1
Note: The dongle is connected directly (no hub).

With /dev/ttyUSB1: sudo python3 Elelabs_EzspFwUtility.py probe -p /dev/ttyUSB1
Traceback (most recent call last):
  File "Elelabs_EzspFwUtility.py", line 798, in <module>
    elelabs.probe()
  File "Elelabs_EzspFwUtility.py", line 535, in probe
    ezsp_status = ezsp.initEzspProtocol()
  File "Elelabs_EzspFwUtility.py", line 292, in initEzspProtocol
    self.ezspVersion = self.sendVersion(self.INITIAL_EZSP_VERSION)
  File "Elelabs_EzspFwUtility.py", line 267, in sendVersion
    return resp[3] # protocolVersion
IndexError: bytearray index out of range

With /dev/ttyUSB0: sudo python3 Elelabs_EzspFwUtility.py probe -p /dev/ttyUSB0
2022/06/20 16:39:52 Elelabs_EzspFwUtility:   Couldn't communicate with the adapter in Zigbee (EZSP) mode, Thread (Spinel) mode or bootloader mode

Regards,

**Comment by achsoftathome** [comment]
Hi, 

There are many problems with this Python script.

If it helps someone, I finally succeeded in switching to Ubuntu/XUbuntu 18.04 64 bits using the following flashing method. 
My device is seen as : ttyUSB0 & ttyUSB1 (the right device is the 1).

Regards,

Arnaud

python3 Elelabs_EzspFwUtility.py flash -p /dev/ttyUSB1 -f ./data/EFR32MG21/ELU0143_MG21_ot_rcp_123_211211.gbl
> 2022/06/21 08:43:39 Elelabs_EzspFwUtility: EZSP adapter in bootloader mode detected:
> 2022/06/21 08:43:39 Elelabs_EzspFwUtility: Gecko Bootloader v1.12.10
> 2022/06/21 08:43:39 Elelabs_EzspFwUtility: Allready in bootloader mode. No need to restart
> 2022/06/21 08:43:40 Elelabs_EzspFwUtility: Successfully restarted into X-MODEM mode! Starting upload of the new firmware... DO NOT INTERRUPT(!)
> .....
> .....
> .....
> .....
> .....
> .....
> .....
>
> 2022/06/21 08:43:57 Elelabs_EzspFwUtility: Firmware upload complete
> 2022/06/21 08:43:57 Elelabs_EzspFwUtility: Rebooting NCP...
> 2022/06/21 08:44:06 Elelabs_EzspFwUtility: Elelabs Thread adapter detected:
> 2022/06/21 08:44:06 Elelabs_EzspFwUtility: Adapter: ELU0143
> 2022/06/21 08:44:06 Elelabs_EzspFwUtility: Firmware: ELElabs-OPENTHREAD/1.2.3.0_GitHub-a935fc51f; EFR32; Dec 11 2021 05:44:34
> 2022/06/21 08:44:06 Elelabs_EzspFwUtility: SPINEL v4.3

**Comment by achsoftathome** [comment]
[Closed]
