### ISSUE TITLE
Tool is not working

### ISSUE THREAD

**Issue by Indept-Studios** [Elelabs/elelabs-zigbee-ezsp-utility#48]
I followed your instructions and first
downloaded the repro and checked the requierments.
Then I entered the `python3 Elelabs_EzspFwUtility.py probe -p /dev/ttyUSB0` command.

I get the following error message.
```
Traceback (most recent call last):
  File "D:\Chris\Downloads\elelabs-zigbee-ezsp-utility-master\Elelabs_EzspFwUtility.py", line 77, in open
    self.serial = serial.Serial(port=self.port,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chris\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\Chris\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "C:\Users\Chris\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port '/dev/ttyUSB0': FileNotFoundError(2, 'Das System kann den angegebenen Pfad nicht finden.', None, 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Chris\Downloads\elelabs-zigbee-ezsp-utility-master\Elelabs_EzspFwUtility.py", line 799, in <module>
    elelabs.probe()
  File "D:\Chris\Downloads\elelabs-zigbee-ezsp-utility-master\Elelabs_EzspFwUtility.py", line 533, in probe
    serialInterface.open()
  File "D:\Chris\Downloads\elelabs-zigbee-ezsp-utility-master\Elelabs_EzspFwUtility.py", line 84, in open
    raise Exception("PORT ERROR: %s" % str(e))
Exception: PORT ERROR: could not open port '/dev/ttyUSB0': FileNotFoundError(2, 'Das System kann den angegebenen Pfad nicht finden.', None, 3)
```

I am on a Windows system and have opened PowerShell as an administrator.
I have also updated the drivers for the port (CP210). Either to 6.7.6.2130 or 11.3.0.176.

`Das System kann den angegebenen Pfad nicht finden` means `System cannot find the specified path`

Let me know if u need anything else

**Comment by Indept-Studios** [comment]
okay... so im on windows... the port has to be COM3 (in my case) not /dev/ttyUSB0 im sry
