### ISSUE TITLE
getResponse inconsistent return value

### ISSUE THREAD

**Issue by FlorianLudwig** [Elelabs/elelabs-zigbee-ezsp-utility#7]
`getResponse` response with two or three  value tuple in different situations. Should be consistent to avoid problems like:

```
Traceback (most recent call last):
  File "Elelabs_EzspFwUtility.py", line 528, in <module>
    elelabs.probe()
  File "Elelabs_EzspFwUtility.py", line 309, in probe
    ezsp_status = ezsp.initEzspProtocol()
  File "Elelabs_EzspFwUtility.py", line 288, in initEzspProtocol
    ash_status = self.ash.sendResetFrame()
  File "Elelabs_EzspFwUtility.py", line 180, in sendResetFrame
    status, response = v # self.getResponse()
ValueError: too many values to unpack (expected 2)
```

**Comment by NilsBohr** [comment]
Fixed
