### ISSUE TITLE
Cannot use the utility to probe or update firmware - ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by thedesp** [Elelabs/elelabs-zigbee-ezsp-utility#8]
Hi, 

I cannot use the ezsp utility to probe or update firmware for my Zigbee USB stick. The error returned is:

```
sudo python3 Elelabs_EzspFwUtility.py probe -p /dev/ttyUSB0

Traceback (most recent call last):
  File "Elelabs_EzspFwUtility.py", line 526, in <module>
    elelabs.probe()
  File "Elelabs_EzspFwUtility.py", line 307, in probe
    ezsp_status = ezsp.initEzspProtocol()
  File "Elelabs_EzspFwUtility.py", line 286, in initEzspProtocol
    ash_status = self.ash.sendResetFrame()
  File "Elelabs_EzspFwUtility.py", line 178, in sendResetFrame
    status, response = self.getResponse()
ValueError: too many values to unpack (expected 2)
```

This is what the USB stick looks like when I made the purchase. I can't tell if this model is supported by the utility.

![2020-12-21 15_47_17-Window](https://user-images.githubusercontent.com/22972545/102757570-1cb12100-43a4-11eb-83a3-f09091e59ea1.png)

**Comment by Tobster77** [comment]
Same issue for my 2018 Elelabs USB stick, Ember EM35x device:
```
openhabian@openHABianDevice:/home/elelabs/elelabs-zigbee-ezsp-utility-master$ sudo python3 Elelabs_EzspFwUtility.py probe -p /dev/ttyUSB0
Traceback (most recent call last):
  File "Elelabs_EzspFwUtility.py", line 526, in <module>
    elelabs.probe()
  File "Elelabs_EzspFwUtility.py", line 307, in probe
    ezsp_status = ezsp.initEzspProtocol()
  File "Elelabs_EzspFwUtility.py", line 286, in initEzspProtocol
    ash_status = self.ash.sendResetFrame()
  File "Elelabs_EzspFwUtility.py", line 178, in sendResetFrame
    status, response = self.getResponse()
ValueError: too many values to unpack (expected 2)
```

**Comment by jmoransalama** [comment]
I'm having the same problem on a Windows 10 machine.

**Comment by sokai** [comment]
**FYI:** Before probing (as root + which fails for me, too) I installed (as root) the packages from `requirements.txt` and the output was as followed …

```
$ pip3 install -r requirements.txt
Collecting pyserial==3.4
  Downloading pyserial-3.4-py2.py3-none-any.whl (193 kB)
     |████████████████████████████████| 193 kB 1.6 MB/s 
Collecting xmodem==0.4.6
  Downloading xmodem-0.4.6.tar.gz (32 kB)
Building wheels for collected packages: xmodem
  Building wheel for xmodem (setup.py) ... done
  Created wheel for xmodem: filename=xmodem-0.4.6-py3-none-any.whl size=34564 sha256=73048847d58d4c9b8c0592ea8594d9780fa6873f88f04a122f4f32d153233dea
  Stored in directory: /root/.cache/pip/wheels/8a/46/14/833413574281b7009c9180fce7c595a7cc1b538e43fcd8b7e7
Successfully built xmodem
Installing collected packages: pyserial, xmodem
Successfully installed pyserial-3.4 xmodem-0.4.6
```
